### ISSUE TITLE
Feature Request : Add view button that links to the demo site.

### ISSUE THREAD

**Issue by jrobertblack** [proteusthemes/one-click-demo-import#100]
Next to Import button it would be nice to add a button maybe called "View" that would open the demo site on a new page
Something like this...

`'import_view_url'            => 'http://your-domain/theme03',`

**Comment by capuderg** [comment]
Hi,

thanks for your request.

The same request already exists in this GH issue: https://github.com/proteusthemes/one-click-demo-import/issues/66

So I will close this issue for now, since it is a duplicate, but this will be added to the plugin, I just don't have an exact date.

Take care!
