### ISSUE TITLE
Errors when uploading a theme style after another theme style

### ISSUE THREAD

**Issue by jrobertblack** [proteusthemes/one-click-demo-import#101]
Not sure If Im doing something wrong, but testing it with my new theme, and seems everything is good when I import a theme style after I reset all of wordpress to a fresh install, but when I import a theme style on top of another theme style that has been loaded there seems to be some things in the customizer that didnt change over, and it looks a little off.

Anyone else have these issues? 
Should the user have to reset wordpress before loading a different theme style. 
Do I have some bugs somewhere in the customizer export?

Cheers

**Comment by capuderg** [comment]
Hi,

the user should not have to reset WP to make a new demo import.

The import of customizer settings should overwrite the existing customizer settings, so maybe double check your customizer export files?

Or are these customizer settings maybe depending on demo content (posts, pages, ...), maybe the IDs are wrong, because of the existing content from the first import?

Which settings are "a little off"?

If you make these two imports separately (each on fresh WP install), do the customizer settings import ok? Everything looks like it should?

Take care!

**Comment by jrobertblack** [comment]
Ya I know about the page issues if there are similar page ids and such, but this is in the customizer, one issue I saw was with one of the fonts setting, the import should have been changed sans, but it stayed serif from the the old theme style.... I have been editing the customizer setting, and uploaded new versions to the sample themes, so they are not fresh settings... that could be the issue... might try to redo all the setting on a fresh install... but the strange thing is if the theme style is loaded on a fresh install it loads fine.... will update when I redo the theme settings on fresh install

**Comment by capuderg** [comment]
That is strange.

Let me know, how it goes with fresh settings.

**Comment by capuderg** [comment]
Hi @jrobertblack,

any progress on this issue? Did you fix it?

Take care!

**Comment by jrobertblack** [comment]
I redid some sample themes and still the problem, and tried using just the customizer import export and the problem is there as well. So I'm thinking something in the settings that is creating a bug. Have you seen any issues with stuff from text areas like shortcodes, quotes, or anything else like that that might cause a bug? I guess I will look through the options and see what was changed and see if I can find a the problem...

**Comment by capuderg** [comment]
Hi,

we had no issues with customizer imports, so I don't have any special instructions, that I could pass to you.

But now, that you said _quotes_, maybe something like that might be causing this issue. Quotes or any other "special" characters might have to be escaped and that might be the problem? I don't know...

Take care!

**Comment by capuderg** [comment]
I hope you solved this issue. Since this is an older issue, I will close it for now.
