### ISSUE TITLE
WooCommerce product price not set to 0

### ISSUE THREAD

**Issue by transbetacism** [proteusthemes/one-click-demo-import#103]
When importing a WooCommerce product with price 0, no price is set (it is left null). When importing the same file with the standard WordPress importer, price is set to 0 as expected.

See attached example.

[free-product-import.xml.zip](https://github.com/proteusthemes/one-click-demo-import/files/925760/free-product-import.xml.zip)

As you can see in the file, price is set to 0:

    <wp:postmeta>
        <wp:meta_key><![CDATA[_regular_price]]></wp:meta_key>
        <wp:meta_value><![CDATA[0]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
        <wp:meta_key><![CDATA[_sale_price]]></wp:meta_key>
        <wp:meta_value><![CDATA[]]></wp:meta_value>
    </wp:postmeta>
    <wp:postmeta>
        <wp:meta_key><![CDATA[_price]]></wp:meta_key>
        <wp:meta_value><![CDATA[0]]></wp:meta_value>
    </wp:postmeta>

**Comment by transbetacism** [comment]
I should note that it worked before WooCommerce 3.0. From that version, they changed something related to products with 0 price. They are no longer shown as Free but are shown as 0 instead.

**Comment by capuderg** [comment]
Hi,

I'll look at this over the weekend...

If you want, you can also create a PR and we will merge it to our plugin, if everything looks ok (this way it will be fixed sooner).

Take care!

**Comment by capuderg** [comment]
Hi @transbetacism,

I've fixed the empty (0 or '') meta data import and it will be available in the next plugin update.

I would like to ask you to test it out with this release candidate: https://www.dropbox.com/s/y5hu9yld5bj3aaz/ocdi-v2.3.0-RC2.zip?dl=1

Let me know how it goes!

Take care!

**Comment by transbetacism** [comment]
Thanks, it worked!

/Joakim
