### ISSUE TITLE
Emit a JS event when import is complete

### ISSUE THREAD

**Issue by ktmn** [proteusthemes/one-click-demo-import#107]
I need to redirect after the import and since it's all AJAX based I have devised a "hack" to watch for the loading gif to disappear and then redirect, but an event would be more cleaner. The event could contain info about what was imported as well, but it's not essential as you can manually set it with PHP during the import and retrieve the info later.

**Comment by capuderg** [comment]
Hi,

sure a custom namespaced JS event would not hurt anyone.

Could you please create a PR for that and we'll merge it into the plugin? That would be great!

Take care!

**Comment by capuderg** [comment]
I've added a simple event trigger here: https://github.com/proteusthemes/one-click-demo-import/commit/3b596ec748a6eda749d40eed0d2e94960cd76042

The custom event is called `ocdiImportComplete`.

**Comment by capuderg** [comment]
Hi,

the plugin update with this added code was just released (available on https://wordpress.org/plugins/one-click-demo-import/).

If you can, please test is out and let me know, if something is not working as it should.

Take care!

**Comment by ktmn** [comment]
Tested, works great, thanks!
