### ISSUE TITLE
All WooCommerce products imported as simple products

### ISSUE THREAD

**Issue by transbetacism** [proteusthemes/one-click-demo-import#108]
My import file contains all different WooCommerce product types, but all products are imported as Simple products (instead of Variable, Grouped etc).

When I import the same file using the native WordPress importer, the products are successfully imported as the correct product type.

[products-with-media_v1-1.xml.zip](https://github.com/proteusthemes/one-click-demo-import/files/981575/products-with-media_v1-1.xml.zip)

**Comment by capuderg** [comment]
Hi,

I think the issue again are missing product types, like:

```
	<wp:term>
		<wp:term_id><![CDATA[15]]></wp:term_id>
		<wp:term_taxonomy><![CDATA[product_type]]></wp:term_taxonomy>
		<wp:term_slug><![CDATA[variable]]></wp:term_slug>
		<wp:term_parent><![CDATA[]]></wp:term_parent>
		<wp:term_name><![CDATA[variable]]></wp:term_name>
	</wp:term>
```

Always try to import with the whole XML files (don't remove things from it).

Take care!
