### ISSUE TITLE
Is there any method to move the plugin page as a section in my own page?

### ISSUE THREAD

**Issue by themevan** [proteusthemes/one-click-demo-import#111]
Hi

Is there any method to move the plugin page content as a section in my theme admin page?

Thanks

**Comment by capuderg** [comment]
Hi,

you want to integrate the OCDI into another admin page (not just move the OCDI plugin page to the other location)?

To answer your question: No, there is not method (easy way) to integrate the plugin page into another admin page.

I've never tried that... You would have to copy the code in `views/plugin-page.php` and also enqueue the JS and CSS scripts on your admin page...

Take care!

**Comment by themevan** [comment]
Thanks for you gave me the right direction.  
I just added a hook into the head of the plugin-page.php file like do_action('demo_importer_header');
Then, it's very easy to add my own page header to the plugin page.

Good plugin!

**Comment by javedskt2006** [comment]
Hello themevan,
Have You did it and is it work fine for you. if its working good plz can you share how to integrate this theme in our admin page in bit more detail. thank you.......
