### ISSUE TITLE
custom post types categories ids get changed on import

### ISSUE THREAD

**Issue by stergosz** [proteusthemes/one-click-demo-import#113]
When i use the OCDI with my demo content while using Visual Composer as a plugin to build my pages, a VC shortcode may use a custom post type category to fetch data with let's say ID=9.

When the import finishes, the categories for the custom post type have different IDs and then the shortcode will not work unless i go to the page and manually change the shortcode to use the same category but now it has a new ID=20.

This breaks my home pages as they need manually to be set after using the importer.

Is there anything that can be done to retain the same ID's or any way others have dealt with this?

Thank you.

**Comment by capuderg** [comment]
Hi @stergosz,

sorry for this late reply...

I see that you already closed the issue... were you able to solve your problem?

**Comment by stergosz** [comment]
I changed from term ids to term slugs and this solved the issue as slugs remain the same after importing the demo content.

**Comment by capuderg** [comment]
great :)

We can't rely on IDs being the same, so this is a good solution.
