### ISSUE TITLE
Failed to import custom taxonomy

### ISSUE THREAD

**Issue by djwd** [proteusthemes/one-click-demo-import#115]
Hi guys,

I'm trying to use your great importer for a premium theme. Everything is importing fine, but this custom taxonomy I have (it's pretty much a tag clone). 

[WARNING] Failed to import custom_taxonomy One
[WARNING] Failed to import custom_taxonomy Two
[WARNING] Failed to import custom_taxonomy Three
[WARNING] Failed to import custom_taxonomy Four

Any insight on what could be the reason and how I could debug this?

**Comment by djwd** [comment]
**Update:** It was an error on my end on registering the custom taxonomy.

**Comment by capuderg** [comment]
Hi,

I'm glad you found the issue and solved it :)

Have a nice day!
