### ISSUE TITLE
Support for WP-CLI

### ISSUE THREAD

**Issue by primozcigler** [proteusthemes/one-click-demo-import#116]
Register commands for so the import can be triggered via WP-CLI. [How to do it](https://make.wordpress.org/cli/handbook/commands-cookbook/#include-in-a-plugin-or-theme).

**Comment by capuderg** [comment]
Was added with this merge: https://github.com/proteusthemes/one-click-demo-import/commit/f0e60fa8437fcb9cbb991a12f58a04ff21f7b72a

Plugin update will be out shortly.
