### ISSUE TITLE
Problem with virtual composer shortcodes

### ISSUE THREAD

**Issue by endritshehu** [proteusthemes/one-click-demo-import#117]
Hello
First let me say your plugin is very good.
I have made a one click demo with all redux, pages, posts, revolution slider and all of that.
The import of the files is ok but it appears that my virtual composer custom shortcodes are not imported.
How to do that. Is there any function to import them.
Thank you

**Comment by capuderg** [comment]
Hi,

first, you probably mean "visual composer" and not "virtual composer", right?

Your custom visual composer shortcodes/elements are added in the visual composer editor and so they should be imported normally, with the content importer.

Is the problem maybe, that you are using specific IDs for posts/pages/categories/tags... in these custom visual composer shortcodes? After importing, the IDs are not the same as on the original (export) site and that might be causing issues for your elements?

Do normal visual composer elements get imported ok and your custom elements do not import (none of them)?

Take care!

**Comment by endritshehu** [comment]
Sorry. 
It is Visual Composer.
The normal vc elements are imported ok.  Only the custom ones are not imported. The theme looks ok 100% but in the VC shortcode mapper has no custom shortcodes.
What to do? Is there any wayy to import all of them?

**Comment by capuderg** [comment]
Hi,

the custom Visual Composer shortcodes/elements should be registered in the theme code in order to be available in the Visual Composer editor and for the OCDI...

Please check, that you register these VC shortcodes correctly.

Take care!
