### ISSUE TITLE
Conflict with WooCommerce Import

### ISSUE THREAD

**Issue by komarovartem** [proteusthemes/one-click-demo-import#118]
Hi. Tested on different environments. Last version of WP and WOO. No other plugins only Woo and One Click Demo Import

If you open Product and then hit Import button your page gets crushed with too many HTTP redirects error. Export works fine. 

Cheers

**Comment by capuderg** [comment]
Hi,

I get the same issue, but I have no idea, why this would happen... The only WooCommerce specific code in our OCDI plugin is this filter function: `woocommerce_product_attributes_registration`. I've disabled it, but the issue remains...

We are also not doing any redirects.

I'll be able to check/debug this issue over the weekend.

Take care!

**Comment by capuderg** [comment]
Hi @komarovartem,

I've found the issue, which was solved with a quick fix: https://github.com/proteusthemes/one-click-demo-import/commit/94e20ec657195930f711cedcbcd3465d6a82f7cc

Thanks for reporting this bug.

We will update the plugin in the following days.

Take care!

**Comment by capuderg** [comment]
The plugin update is live now :)

**Comment by komarovartem** [comment]
Thank you )
