### ISSUE TITLE
Feature Request: Uninstall feature

### ISSUE THREAD

**Issue by herculesdesign** [proteusthemes/one-click-demo-import#121]
Hi,
great plugin. Are you planning to add the Uninstall button that the user will be able to remove installed demo data ?
Kind Regards
CJ

**Comment by capuderg** [comment]
Hi @herculesdesign,

we were thinking about this in the past, but we always came to a conclusion, that removing the imported content is a bit of a dangerous task. The user does not know exactly, which pages/posts/... were imported and which were created by him or which of the pages that were imported and he modified. This delete functionality, would delete these modified pages and the user would lose his content.

WordPress has a decent bulk actions system in place, so deleting many pages/posts/... at once is not that hard and time consuming, so we decided to not include such functionality to the OCDI plugin.

Take care!
