### ISSUE TITLE
Content not being imported

### ISSUE THREAD

**Issue by Wassim-Haddar** [proteusthemes/one-click-demo-import#123]
Hello gays,

first of all, thanks a lot for this great plugin :)

I'm trying to integrate it with our theme, it seems that everything is working correctly (widgets and Redux) unless the XML content (pages, posts...).

According to the log, there is no note about the XML content file.
Please note that I even tried with manual upload, nothing happened.
Also note that the XML file is correct, I tried with the standard WP import and it worked correctly.

Here is the log:

> ---Downloaded files---
> The import files for: BlogWizaTheme were successfully downloaded!
> Initial max execution time = 500000000
> Files info:
> Site URL = http://localhost:8080/BlogWizaTheme/wordpress
> Data file = F:\BlogWizaTheme\wordpress/wp-content/themes/wiza/framework/demo-importer/demo/main/wiza-content.xml
> Widget file = F:\BlogWizaTheme\wordpress/wp-content/themes/wiza/framework/demo-importer/demo/main/wiza_widgets.wie
> Customizer file = not defined!
> Redux files:
> wiza_options -> F:\BlogWizaTheme\wordpress/wp-content/themes/wiza/framework/demo-importer/demo/main/wiza_redux.json 
> 
> 
> ---Importing widgets---
> top-bar-section : Sidebar does not exist in theme (moving widget to Inactive)
> 
> Text - No Title - Widget already exists
> 
> ---Importing Redux settings---
> Redux settings import for: wiza_options finished successfully!

As you can see, it just logs the Widgets and the Redux import process.

Any idea ?

Thank you :)

**Comment by Wassim-Haddar** [comment]
Issue resolved.

Here is the reason and the solution in case if someone encounter the same issue:
For some reason, the XML file generated by Wordpress contained 2 empty lines at the top, so when importing it fails. These 2 lines should be removed.

Take a look here: https://prnt.sc/h348gv

Hope it will helps someone.

Thank you gays again for this great plugin, it helps us a lot and saved our time :)

**Comment by capuderg** [comment]
Hi @Wassim-Haddar,

thanks for sharing the issue and solution with us.

Take care!
