### ISSUE TITLE
I am using Codestar instead of Redux Theme Panel Settings Problem

### ISSUE THREAD

**Issue by pinethemes** [proteusthemes/one-click-demo-import#124]
I am using Codestar instead of Redux Theme Panel Settings I am having a problem. I can save the Codestar framework theme panel settings, but it is not compatible with your plugin, how can I solve this problem. How can I include the txt file downloaded from the Codetstar theme panel into the demo files, it always gives an error.

**Comment by capuderg** [comment]
Hi,

our plugin is only compatible with WP import (content), widgets import, customizer settings import and Redux framework. For any other framework, like in your case, you would have to hook into the plugin actions and import your framework settings yourself. Each of these "frameworks" has it's own importer, so you would have to look at that code and use it in our OCDI plugin action hooks to import it.

You should use the OCDI after import hook.

I'm sorry, but that's as much as I can help you.

Take care!
