### ISSUE TITLE
Exporting from Redux Framework for OCDI

### ISSUE THREAD

**Issue by winslowpaul** [proteusthemes/one-click-demo-import#134]
Hey,

https://twitter.com/capuderg/status/957212399660097536

I'm wanting my theme to support OCDI, however I'm using the Redux Options Framework and I don't appear to be able to export a JSON file, which the following post instructs me to do: http://proteusthemes.github.io/one-click-demo-import/

Any help would be much appreciated.

Cheers,
Paul

**Comment by capuderg** [comment]
Hi Paul,

in the Redux plugin, you should have an "import/export" menu item and on that page, there should be an "export options" section, with a "Download" button, which should create the JSON file you need.

At least that's how it was, when we implemented this feature... As Primož said, we don't use the Redux framework in our themes. So, please let me know, if that worked for you, or not, so I can then investigate further if needed.

Take care!

**Comment by winslowpaul** [comment]
Hi Grega,

Thanks for the speedy response!

The Export option appears to be a PHP file, or raw copy-paste data, definitely can't find a JSON option.

Any help would be appreciated.

**Comment by capuderg** [comment]
Hi Paul,

I've just installed the Redux Framework plugin on my test site. Then I allowed the plugin to create demo options, so I had something to work with, then I went to Import/Export and clicked on the "Download Data File" and it downloaded the needed JSON file.

Here is a screenshot: https://www.awesomescreenshot.com/image/3135028/03f41300f9435a766179f32973d6d5fe

Take care!
