### ISSUE TITLE
Suggestion (define demos array via endpoint url json)

### ISSUE THREAD

**Issue by wpexplorer** [proteusthemes/one-click-demo-import#138]
Great plugin!

I just wanted to propose a suggestion. Currently you need to define an array of demos via the pt-ocdi/import_files filter as an array.

It would be cool if you could also return a live URL with json data, this way if the theme has a lot of demos and the demos are hosted on a multi-site the demos array could be setup dynamically.

Example:

```
add_filter( 'pt-ocdi/import_files', function() {
	return 'theme-demo.com/demo-json/'
} );
```

This way as you add new demos the theme itself doesn't need to be updated, just the endpoint url.

It would be very easy to add the tweak and I'd be happy to submit a pull request if you guys are down ;)

- AJ

**Comment by capuderg** [comment]
Hi,

thank you for your kind words and offer to help.

I just have a question... Is it not possible to read this remote JSON file in the filter itself, decode the JSON into an array and return that? Or am I missing something?

**Comment by wpexplorer** [comment]
@capuderg - You are correct ;)

I was thinking that the plugin could have a simple check to auto decode it if a url was passed to the filter instead of an array.
