### ISSUE TITLE
Docs mentions using get_template_directory() but it should be get_template_directory_uri()

### ISSUE THREAD

**Issue by wpexplorer** [proteusthemes/one-click-demo-import#139]
On your main landing page - http://proteusthemes.github.io/one-click-demo-import/ - under "**What about using local import files (from theme folder)?**" it recommends using get_template_directory() but it should instead be an absolute URL via get_template_directory_uri()

**Comment by capuderg** [comment]
No, the use of `get_template_directory` is correct, because we need an absolute path to the import file  and not an URL of the import file.
