### ISSUE TITLE
Importing multiple demos show incorrect images?

### ISSUE THREAD

**Issue by ViktorAndonov** [proteusthemes/one-click-demo-import#141]
First, let me say great plugin!

When you have multiple demos, the first import goes great, everything is in place.

But when you try to import another demo, most of the images are incorrect, the second demo shows images from the first demo, and some images are completely missing.

I've tried on a live server, locally, multisite, and on multiple separate installations, the problem still persists, the code is from the example here on GitHub.

I don't know what causes this and have you had a situation similar to this?

**Comment by capuderg** [comment]
Hi @ViktorAndonov,

thanks! :)

Why would you like to import multiple demos in the same WP site?

The IDs of the images, post, categories, ... will not be correct, that's why the additional imports don't look good.

The OCDI plugin is meant for importing a single demo import on one WP site.

Take care!

**Comment by ViktorAndonov** [comment]
Thanks for the replay.

I see I don't want personally what to import multiple demos, I've just trying to predict what users might do and usually, they click every blue button they see and later ask for help.

Also, is not mentioned that you can import just one demo, I think this is important information to know.

Anyway still, a great plugin hopefully in future multiple imports will be a feature.

**Comment by capuderg** [comment]
If you want, you can edit the text on the demo import section, to warn users, not to import multiple times, if you really think this is necessary.

Look at the "I’m a theme author and I want to change the plugin intro text, how can I do that?" question in the FAQ for further instructions : https://wordpress.org/plugins/one-click-demo-import/#faq

**Comment by ViktorAndonov** [comment]
Yes, a notice is will definitely be needed.
