### ISSUE TITLE
How to check require plugins are all installed and activated?

### ISSUE THREAD

**Issue by HW-Siew** [proteusthemes/one-click-demo-import#142]
Hi, how can i check all required plugins are installed and activated? Or, prompt user to install or activate necessary plugins?

Thanks for your advice.

**Comment by capuderg** [comment]
Hi,

you can use the TGMPA plugin installer: http://tgmpluginactivation.com/ for requiring the plugins to your theme. 

If you want to add a "check" before the demo import starts. You can hook into the `pt-ocdi/plugin_intro_text` filter hook and add a warning notice, if the plugins are not activated (you can check that manually). You can find more info about the filter hook here: https://wordpress.org/plugins/one-click-demo-import/#faq in the "I’m a theme author and I want to change the plugin intro text, how can I do that?" question.

Take care!
