### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by mugurcagdas** [proteusthemes/one-click-demo-import#148]
Dear Sir/Madam,

I am computer engineer and graphic designer. I use your plugin in my customers' websites. I appreciate that.
I am writing you because I want to design a logo for this plugin.
May I ask, do you need a logo for this plugin?

Kindly waiting your answer.

Best Regards,
Musa Ugur Cagdas
Computer Engineer/Graphic Designer

**Comment by capuderg** [comment]
Hi Musa,

thank you for your offer, but we don't need a logo for this plugin.

Thank you can take care!
