### ISSUE TITLE
Change default plugin notice text

### ISSUE THREAD

**Issue by chozze** [proteusthemes/one-click-demo-import#152]
Please, include a filter for import notice

```
<div class="ocdi__intro-notice  notice  notice-warning  is-dismissible">
	<p><?php esc_html_e( 'Before you begin, make sure all the required plugins are activated.', 'pt-ocdi' ); ?></p>
</div>
```

Would be great if we can customize this message for users..

thanks

**Comment by capuderg** [comment]
Hi,

the whole intro text (the above text included) is filterable with this filter `pt-ocdi/plugin_intro_text`.

Check the answer to the "I’m a theme author and I want to change the plugin intro text, how can I do that?" question here: https://wordpress.org/plugins/one-click-demo-import/ in the FAQ section.

Take care!

**Comment by chozze** [comment]
ouch! sorry I must missed that..thanks a lot mate!

**Comment by capuderg** [comment]
No problem :)
