### ISSUE TITLE
Conflict with Elementor 2.1.1 

### ISSUE THREAD

**Issue by DeoThemes** [proteusthemes/one-click-demo-import#156]
Hey.
I'm using your plugin for demo import in our theme and it was working well until Elementor released new version 2.1.1. Now all the demo content is broken upon importing. I've tested it with a native WP importer, which working just fine. So I'm trying to identify the issue.

Please check this issue - https://github.com/pojome/elementor/issues/4947

Here is the demo XML reference:
https://www.dropbox.com/s/oxz435plv83fqxp/demo-content.xml?dl=0

**Comment by capuderg** [comment]
Hi,

looking at the discussion of the above link, they changed their code and should be working now? They are just waiting to merge it into the master and release a new version.

Take care!
