### ISSUE TITLE
Let me know which version is recommended.

### ISSUE THREAD

**Issue by snsworks** [proteusthemes/one-click-demo-import#158]
WordPress, PHP, Database 
Let me know the recommended version of these
All versions of PHP7.2 have been installed. But clicking the demo one click button says that the installation is complete.

But nothing happens.

Please solve it.

**Comment by capuderg** [comment]
Hi,

do you have the php-xml PHP module installed? More info about this issue: https://github.com/proteusthemes/one-click-demo-import/blob/master/docs/import-problems.md#already-experienced-server-errors

Take care!
