### ISSUE TITLE
Reason: 404 - Not Found

### ISSUE THREAD

**Issue by aredorange** [proteusthemes/one-click-demo-import#163]
After activating the One Click Demo plugin, after trying to import my data, got this message:

An error occurred while fetching file from: https://updates.wolfthemes.com/phase-package-1-1-2phase/demos/main/content.xml!
Reason: 404 - Not Found.

How is it possible it does not exist, if I have just bought the theme, which mentions One Click Demo and activated the plugin?

**Comment by capuderg** [comment]
Hi,

this is not an issue with the plugin, but the import file that your purchased theme is providing.

Please contact your theme author and ask them to fix the import files for your theme.

Take care!
