### ISSUE TITLE
Massive site and OCDI

### ISSUE THREAD

**Issue by vlthemes** [proteusthemes/one-click-demo-import#168]
Hello team.
I have a massive site and my customers can not install demo. Absolutely everyone. Half content is imported.

Attachments looks good. Some pages did`t imported.

Maybe I can use demo import parts? (media, posts, pages etc.)

THEME: http://wp.vlthemes.com/leedo/

**Comment by capuderg** [comment]
Hi,

so you used OCDI before in other themes and it's working OK, but now in this theme, it will not import? Did you not test the import before launching the theme?

All media files get imported and some pages are missing? How many media files does the demo content have?

What is the output of the plugin (does the import finish with success, with error, or something else)? What does the PHP error logs say?

Take care!

**Comment by vlthemes** [comment]
Thank you for your answer!

> so you used OCDI before in other themes and it's working OK, but now in this theme, it will not import? Did you not test the import before launching the theme?
Yes, because this is biggest theme which we did. We use OCDI in other themes and all looks good. Usually we did small portfolio themes with a couple of images.

> All media files get imported and some pages are missing? How many media files does the demo content have?
Yes, some page is missing. We have this menu after demo import with missing pages http://take.ms/8fTKp
218 attachments 

What is the output of the plugin (does the import finish with success, with error, or something else)? What does the PHP error logs say?
OCDI says that the demo content ended successfully. http://take.ms/nGMrw
Plugin Log here http://take.ms/ov7Nd
Nothing PHP errors

We can send our theme and you can check it.

**Comment by capuderg** [comment]
I see the import goes till the end, so you get the green success notice on the end of the import?

Did you check, if the pages in your menu are actually imported (are in the "Pages" section), but just the menu is "corrupted"? This way, only the menu is the issue and not the content import?

**Comment by capuderg** [comment]
It's very strange, that the importer would not output an error if a pages fails to import... Did you try to make a new XML file (export) and try the import with that new file?

**Comment by vlthemes** [comment]
I tried that 5 times. But default importer works good.

**Comment by capuderg** [comment]
Hi,

try to open the XML file in google chrome browser, you will see that there is an encoding issue in it:

<img width="1429" alt="screen shot 2018-10-29 at 07 27 24" src="https://user-images.githubusercontent.com/9714134/47632876-351eab80-db4c-11e8-869d-26362207799d.png">

That is probably the issue why the import fails...

Take care!

**Comment by vlthemes** [comment]
Hmm.
Maybe you know how can I fix this?
I used default exporter for this xml file.

**Comment by capuderg** [comment]
I'm not sure, but you should view the line 16691 and see if you can change the content in your demo site that is pointing to this line... Maybe there are some strange characters... Try to remove that content on your demo site and type it out, maybe you copy-pasted this content and it added some strange content...

**Comment by vlthemes** [comment]
Thank you sou much. You are right.

I found phantom space between words.

I`ll try to import demo again.

**Comment by vlthemes** [comment]
Solved. Thank you so much for your help.

You are the best.

**Comment by capuderg** [comment]
no problem :)
