### ISSUE TITLE
"That's it, all done!" Notice

### ISSUE THREAD

**Issue by JakJakson** [proteusthemes/one-click-demo-import#176]
Hey guys, 

Firstly thank you fo this amazing plugin!

Just a quick question - is there any way to modify the text on the "success notice":

"That's it, all done!
The demo import has finished. Please check your page and make sure that everything has imported correctly. If it did, you can deactivate the One Click Demo Import plugin, because it has done its job."

Cheers!
Jakson

<img width="1104" alt="all-done-notice" src="https://user-images.githubusercontent.com/47223192/52177114-537fed00-27b4-11e9-872f-3b06c61ddec7.png">

**Comment by primozcigler** [comment]
Hi @JakJakson and thanks!

As seen [here](https://github.com/proteusthemes/one-click-demo-import/blob/409ee02a0b0f54d5d9bccc283c4ed48448a1eb21/inc/OneClickDemoImport.php#L407) at the moment that can only be changed by translating this string. But if you'd need that functionality you can submit a PR with an enhancement and I'll be happy to merge it.

**Comment by JakJakson** [comment]
Hey @primozcigler !  thanks for this  - I used the translate string recommendation  - worked like a charm - It was to point the user to update their permalinks.  Here's the code I sued in case anyone else needs it:

`<?php

//  Update the OCDI Success Notice
 
add_filter( 'gettext', 'translate_ocdi_strings', 999, 3 );
 
function translate_ocdi_strings( $translated, $text, $domain ) {
	
		$url = admin_url( '/options-permalink.php' ) ;
		$newtext= 'The demo import has finished. Please check your site and make sure that everything has imported correctly. If it did, you can deactivate the %3$sOne Click Demo Import%4$s plugin, because it has done its job.
		
		<br><br>
		You may need to <b>Save your Permalinks settings</b>  - use the link below to do that now.
		
		<br>
		<a class=".wp-core-ui .button-primary" href="' . $url . '">Save Permalinks <span class="dashicons dashicons-arrow-right-alt"></a> <br>';
 


// STRING 1
$translated = str_ireplace( 'The demo import has finished. Please check your page and make sure that everything has imported correctly. If it did, you can deactivate the %3$sOne Click Demo Import%4$s plugin, because it has done its job', $newtext, $translated );


/* 
// STRING 2
$translated = str_ireplace( 'Original Text', 'New Text', $translated );
*/

// ETC.
 
return $translated;
}

?>`
