### ISSUE TITLE
Do not import images

### ISSUE THREAD

**Issue by anteksiler** [proteusthemes/one-click-demo-import#178]
Is there anyway we can choose not to import images with the xml import? 

This could be a solution for customers who are having trouble importing.

**Comment by anteksiler** [comment]
Just saw this code:

`$importer_options = apply_filters( 'pt-ocdi/importer_options', array(
			'fetch_attachments' => true,
		) );
`

Is there anyway we can access this using JS before import? I would like to show a checkbox to toggle this.

**Comment by primozcigler** [comment]
Hey,

Yes, that filter should be used to turn off the import of images. However, at the moment there are no UI settings or out of the box ways to access this in the JS. With some tinkering and using the hooks already in the plugin I'm quite sure it would be possible to do.

If you implement it, I'd be more than happy to merge the PR.

**Comment by anteksiler** [comment]
@primozcigler Could you give me some pointers? I saw that the Importer instance is generated before the import is started, so the hooks are all after the start of the import.

**Comment by anteksiler** [comment]
Hi @primozcigler you there? :)
