### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by Nanosergio** [proteusthemes/one-click-demo-import#185]
Hi Grega. Thank you very much for your plugin.
This message is not to inform of any issue but to ask you for an request.
I want to create a multisite where my users can register and have their own subsite. I'd like to insert the choice of the predefined theme in the registration form. This is in a frontend page.
I'd prefer to display the predefined templates in the frontend.  If you don't need a lot of time, could you do a shortcode?
Again, thank you for your dedication

**Comment by primozcigler** [comment]
Hi,

Thank you for suggestion, but we don't have in roadmap to create such a shortcode. If you decide to code it it would be great that you submit a pull request and if it looks good, it might be merged to the plugin itself.
