### ISSUE TITLE
Import failed. Error: OK (200)

### ISSUE THREAD

**Issue by lucassuar** [proteusthemes/one-click-demo-import#188]
Hi there,

I am trying to import demo from a theme using the 'one-click-demo-import' plugin but I get an Error: OK (200).

I also tried the manual method by uploading the xml, dat and wie files but still getting the same error.

My PHP version on my hosting provider is 7.0 and the hosting setting are the following (Advised by the theme author):

max_input_vars (default is 1000) set to 3000
post_max_size (default is “8M”) set to 2000M
upload_max_filesize (default is “2M”) set to 64M
max_execution_time (default is “30”) set to 180
max_input_time (default is “-1”) set to 180
memory_limit (default is “128M”) set to 3000M

Any idea of whats wrong with it? Thanks in advance!

**Comment by Nanosergio** [comment]
Have you tried this [SOLUTION](https://github.com/proteusthemes/one-click-demo-import/issues/112#issuecomment-311998754)?

**Comment by lucassuar** [comment]
Yes, I tried but didnt work. It is solved though.

I contacted my hosting provider and they increase all variables even more. I still getting the error when I attempt to do the import but everything was imported successfully. 

Thanks for your reply!
