### ISSUE TITLE
Widget Import Error

### ISSUE THREAD

**Issue by anteksiler** [proteusthemes/one-click-demo-import#19]
Getting this error:
`<b>Notice</b>:  Undefined variable: widget_output in <b>one-click-demo-import.php</b> on line <b>378</b><br />`

**Comment by capuderg** [comment]
Hi Ant,

thanks for reporting this bug. I will fix this and publish a new version of the plugin this weekend.

Could you send me the widgets import file you were using, when this bug occurred?

Thanks!
