### ISSUE TITLE
.travis.yml file

### ISSUE THREAD

**Issue by primozcigler** [proteusthemes/one-click-demo-import#2]
You still have `.travis.yml` file. If there is no CI integration it should be removed. Or better yet, if you can write some unit tests, please do so and integrate with Travis CI.

**Comment by primozcigler** [comment]
Also, phpunit.xml and tests/ should be either configured or deleted.

**Comment by capuderg** [comment]
I've removed the files for now, but we'll add them back for future plugin update (revert this commit: 34e3da461c75d1764255528bcbc33374c31afbd2).

**Comment by capuderg** [comment]
I've added some phpunit tests and instead of Travis CI, we use Codeship.

More tests should/will be written, when the rewrite will be complete.
