### ISSUE TITLE
Test the plugin on lower version of PHP

### ISSUE THREAD

**Issue by capuderg** [proteusthemes/one-click-demo-import#22]
Test the plugin on lower version of PHP (minimal WP requirement), because of composer (needs at least 5.3)...

**Comment by capuderg** [comment]
The composer is not an issue, since we do not use autoload...

When I tested with PHP version 5.2.x, the issue was Singleton pattern of the main plugin class (which also requires version 5.3.x). The plugin does not want to activate, because it generates a fatal error and there is nothing we can do inside the plugin to fix that, except to not use a singleton pattern (but we will not do that).

I've added a FAQ item in the readme, explaining what the problem is (old PHP version).

**Comment by primozcigler** [comment]
> but we will not do that

:+1:

**Comment by capuderg** [comment]
Maybe we can check for PHP version lower then 5.3 and display an admin notice (and not instantiate the singleton class).

support ticket: https://wordpress.org/support/topic/fatal-error-on-php-52-visible-only-with-debug-mode-enabled?replies=1#post-8408833
