### ISSUE TITLE
Import Widgets after Theme Options

### ISSUE THREAD

**Issue by anteksiler** [proteusthemes/one-click-demo-import#23]
I have added the below code to import Theme Options before the widgets are imported. I need this because theme options allows creation of additional sidebars:
````
/*
		 * 3. Import Theme Options.
		 */

		if ( ! empty( $selected_import_files['options'] ) ) {
			$this->thb_import_options( $selected_import_files['options'] );
		}
		
		/*
		 * 3. Import widgets.
		 */

		if ( ! empty( $selected_import_files['widgets'] ) ) {
			$this->import_widgets( $selected_import_files['widgets'] );
		}
```
However, since it takes time to import the theme options, widgets are not assigned. What can I do to delay the widget import or wait for the options import?

**Comment by capuderg** [comment]
Hi Ant,

we can add a wp action for before widget import, like the existing `pt-ocdi/after_import` action? Maybe someone else might find it useful as well...

That should solve your issue as you can add whatever code you want in that action...

**Comment by capuderg** [comment]
Hi Ant,

I've added a wp action, before the widget import called `pt-ocdi/before_widgets_import`.

It will be available in the next plugin version.
