### ISSUE TITLE
Much faster import when not creating thumbnails

### ISSUE THREAD

**Issue by primozcigler** [proteusthemes/one-click-demo-import#25]
Benchmarked on shared hosting, structurepress-pt theme:

```
Create thumbnails: 2m23s
Ignore thumbnails: 51s
```

Let's discuss (next week).

**Comment by capuderg** [comment]
I would keep the code for disabling generation of the different size images (thumbnails), but I would add a filter to it, so that others can enable this option if needed...

**Comment by capuderg** [comment]
I've added a filter, so thumbnail regeneration can be enabled, if users wish so...

I'm closing this issue, but if you want to discuss it more, please reopen it.
