### ISSUE TITLE
Import content without downloading the XML file first...

### ISSUE THREAD

**Issue by capuderg** [proteusthemes/one-click-demo-import#26]
The content importer is using `XMLReader`, which can also accept an URL (not just a local file), but the current method of the importer `import_start` is checking if the parameter is a file, so we would have to extend the importer class and overwrite that method.

We could probably do the same for the widgets file. In that case there would be no download part of the plugin flow.

What do you think @primozcigler?

**Comment by primozcigler** [comment]
Actually I don't see any major improvement if we don't save XML file locally. It might feel a bit leaner, but that's all there is (I suppose).
