### ISSUE TITLE
Vendor folder is missing

### ISSUE THREAD

**Issue by FrankM1** [proteusthemes/one-click-demo-import#27]
Hi, great plugin. 

You should add a note that one needs to run 'composer install' before using the plugin. Otherwise it'll throw a fatal error.

**Comment by capuderg** [comment]
Hi Frank,

this is just the repository for the plugin. You can get the stable release on wordpress -> here: https://wordpress.org/plugins/one-click-demo-import/

I would suggest that you download the plugin there :)

Take care!
