### ISSUE TITLE
Log files - how to access them if we don't have FTP details?

### ISSUE THREAD

**Issue by primozcigler** [proteusthemes/one-click-demo-import#30]
Is there a way to access the importer log files even if we don't have FTP details? I've checked, they don't show in the media library, nor the name can be guessed as it depends to the time when the importer was run down to 1 second accuracy.

@capuderg it would be best to write some sort of the docs (I recommend the `docs/` folder within this repo) for the theme authors how to debug these things - sort of FAQ, what to do when the specified error codes occur and what is the solution.

- [x] add the log file to the media section
- [x] create "docs" page for different import cases and how to solve them

**Comment by capuderg** [comment]
Yup, great idea.

- [ ] add the log file to the media section
- [ ] create "docs" page for different import cases and how to solve them

**Comment by capuderg** [comment]
@primozcigler did you have something like this in mind:
https://github.com/proteusthemes/one-click-demo-import/blob/master/docs/import-problems.md

I'll update the docs (and add new pages), when new issues arise, that we can't fix in the plugin itself.

**Comment by primozcigler** [comment]
I couldn't ask for anything better than this. Perfect @capuderg !

The only improvement I could think of (if if is improvement at all, I don't know) is that you could setup these docs on [gh-pages](https://pages.github.com/). Decide yourself, even I don't know if I'd do it as markdown here on GH is great!

**Comment by capuderg** [comment]
I was actually also looking at gh-pages, but then decided, that markdown is much easier than writing html :)

**Comment by primozcigler** [comment]
Agreed.
