### ISSUE TITLE
Issues while importing menus.

### ISSUE THREAD

**Issue by anteksiler** [proteusthemes/one-click-demo-import#35]
Let's say that I have a menu named "Top Menu", after the import is complete and I visit Appearances > Menu, I see that there 2 menus,
First is "Top Menu" with 0 menu items.
Second is "34" (probably the id?) with "Top Menu" 's items.

**Comment by capuderg** [comment]
Hi,

this was an issue in older versions of the "content import" we are using in this plugin, however it was already fixed. Please use the latest version of our plugin here: https://wordpress.org/plugins/one-click-demo-import/

Please reopen this issue, if the problem persists with the latest version of the plugin.

Take care!
