### ISSUE TITLE
Work with Reduxframework Options import

### ISSUE THREAD

**Issue by HipsterLab** [proteusthemes/one-click-demo-import#37]
This is good plugins but i think it need have ReduxFramework option import. Thank you for release free plugins.

**Comment by capuderg** [comment]
Hi,

thanks for the kind words :)

Regarding the Redux framework: There is no Redux support in this plugin nor are there any plans to include it.

You could probably import your Redux options "manually" in the `pt-ocdi/after_import` action, with some custom coding.

See also: https://github.com/proteusthemes/one-click-demo-import/issues/28
