### ISSUE TITLE
not working on custom admin page.

### ISSUE THREAD

**Issue by anarerdene** [proteusthemes/one-click-demo-import#53]
I create named "welcome-dashboard" in admin menu. 

$default_settings['parent_slug'] = 'welcome-dashboard';

**Comment by capuderg** [comment]
Hi,

I just tried it with this code and it works ok:

```
function ocdi_plugin_page_setup( $default_settings ) {
	$default_settings['parent_slug'] = 'tools.php';
	return $default_settings;
}
add_filter( 'pt-ocdi/plugin_page_setup', 'ocdi_plugin_page_setup' );
```

Maybe the issue is with your "welcome-dashboard" admin page?

Please try the above code and see, if the **Import Demo Data** menu item is visible under *wp-admin -> Tools*.

**Comment by anarerdene** [comment]
hi,

Your right. Plugins works all wordpress default pages. index.php, tools.php and themes.php etc.
I created custom admin menu like this.

function my_admin_menu() {
		add_menu_page( 
			'Newsbox Dashboard', 
			'Newsbox', 
			'administrator',
			'welcome-dashboard', 
			'welcome_page', 
			get_template_directory_uri(). '/assets/img/dashboard/av-logo.png',
			2
		);
	}


and tried 

function ocdi_plugin_page_setup( $default_settings ) {
    $default_settings['parent_slug'] = 'welcome-dashboard';
    return $default_settings;
}
add_filter( 'pt-ocdi/plugin_page_setup', 'ocdi_plugin_page_setup' );

and menu replaced right. But url result is.

wp-admin/pt-one-click-demo-import

i think right url is. wp-admin/admin.php?page=pt-one-click-demo-import

**Comment by capuderg** [comment]
Hi,

I just tried this and it worked for me. I used this quick test code:

```
function ocdi_add_menu_item() {
	add_menu_page( 'Newsbox Dashboard', 'Newsbox', 'activate_plugins', 'newsbox-site', 'newsbox_site_output' );
}
add_action( 'admin_menu', 'ocdi_add_menu_item', 9 );


function newsbox_site_output() {
	echo "test";
}


function ocdi_plugin_page_setup( $default_settings ) {
	$default_settings['parent_slug'] = 'newsbox-site';
	return $default_settings;
}
add_filter( 'pt-ocdi/plugin_page_setup', 'ocdi_plugin_page_setup' );
```

I also tried the import and it worked as well...

Take care!
