### ISSUE TITLE
I have two questions

### ISSUE THREAD

**Issue by nicolas92** [proteusthemes/one-click-demo-import#56]
Hello,

First of all, thank you for creating this plugin, it is great :)

I created a theme with several demos to present the theme. I created a "Custom CSS" tab in the WordPress dashboard where there is a textarea to make it easy for users to add CSS without child theme.
For each demos, I put the css in a "custom-css.txt" file so that it is easy to import manually, just open this file and then copy/paste the css in the textarea.

I have two questions:

1. Is it possible to import the "custom-css.txt" file with your plugin?

I tried the following function but it imports the url of the file and not its contents:

```
function import_css() {

	// Var
	$css_file 	= 'http://my-url.com/wp-content/demos/demo1/custom-css.txt';

	if ( $css_file ) {
		set_theme_mod( 'custom_css', $css_file);
	}

}
add_filter( 'pt-ocdi/after_import', 'import_css' );
```

2. All my demos have been created with the free plugin Elementor, is it possible to import the pages created with this plugin?
They have their own import/export system, so I think users will have to do it manually but it would be great if they could import all my demos without doing anything manually.

Can you help me with his two questions?

Thank you so much :)

**Comment by capuderg** [comment]
Hi,

thanks! :)

About the CSS import... You will have to fetch the data from your `$url`, with PHP, use `wp_remote_get` or simply with `file_get_contents`. Once you get the content you can set the theme_mod option as you did in the example...

About the Elementor import... I'm sorry, but you would have to code the seperate importer yourself. You should be able to hook to the `pt-ocdi/after_import` action and execute the import normally.

Take care!

**Comment by nicolas92** [comment]
Thank you so mush, I'll try all that :)

**Comment by capuderg** [comment]
No problem :)

**Comment by nicolas92** [comment]
It works perfectly, thank you very much :)It works perfectly, thank you very much :)
