### ISSUE TITLE
Assign pages and menus for multiple demos

### ISSUE THREAD

**Issue by nicolas92** [proteusthemes/one-click-demo-import#57]
Hello,

How to assign the pages front page and blog page according to the selected demo?
On some demos, there is no page home or blog assigned.
In your faq, the "ocdi_after_import_setup" function is for a single demo, how can I make to assign imported pages and menus for multiple demos?

Can you help me with this by giving me an sample function?

Thank you a lot :)

**Comment by capuderg** [comment]
Hi,

please take a look at the FAQ section of the plugin, here: https://wordpress.org/plugins/one-click-demo-import/faq/

The multi demo import after install action is described in the **How to handle different "after import setups" depending on which predefined import was selected?** section.

Take care!

**Comment by nicolas92** [comment]
Hi, I managed to do it, thank you very much :)
