### ISSUE TITLE
Automatically assign WooCommerce pages

### ISSUE THREAD

**Issue by nicolas92** [proteusthemes/one-click-demo-import#58]
Hello
I added a small code to automatically assign the Woocommerce pages after import, can it be added to version 2.0 of the plugin?

Here is the code:
```
function assign_woo_pages() {

	// WooCommerce pages
	if ( class_exists( 'WooCommerce' ) ) {

		$woopages = array(
			'woocommerce_shop_page_id' 				=> 'Shop',
			'woocommerce_cart_page_id' 				=> 'Cart',
			'woocommerce_checkout_page_id' 			=> 'Checkout',
			'woocommerce_pay_page_id' 				=> 'Checkout &#8594; Pay',
			'woocommerce_thanks_page_id' 			=> 'Order Received',
			'woocommerce_myaccount_page_id' 		=> 'My Account',
			'woocommerce_edit_address_page_id' 		=> 'Edit My Address',
			'woocommerce_view_order_page_id' 		=> 'View Order',
			'woocommerce_change_password_page_id' 	=> 'Change Password',
			'woocommerce_logout_page_id' 			=> 'Logout',
			'woocommerce_lost_password_page_id' 	=> 'Lost Password'
		);

		foreach ( $woopages as $woo_page_name => $woo_page_title ) {
			$woopage = get_page_by_title( $woo_page_title );
			if ( isset( $woopage ) && $woopage->ID ) {
				update_option( $woo_page_name, $woopage->ID );
			}
		}

	}

}
add_filter( 'pt-ocdi/after_import', 'assign_woo_pages'  );
```

**Comment by capuderg** [comment]
Hi,

I'm sorry, but we can't add this directly to the plugin code... Not all themes are using WooCommerce plugin. You will have to use this code as you have it now (hooked to the after import action hook).

Take care!

**Comment by nicolas92** [comment]
Hello, okay, the code will serve people who use woocommerce :)
An unrelated question, do you know when you release version 2.0 of your plugin?
Thank you very much.

**Comment by capuderg** [comment]
We are working on this plugin mainly on our free time, so everything is going a bit slower, but I think we should have the update by the end of this month (I can't make any promises).

Take care!

**Comment by nicolas92** [comment]
Thank you very much, it's a great plugin.
I'll wait for thumbnails style that will be much better for multiple demos.
I noticed that several premium themes like Avada use a json file to import their demos with widgets, menus, customizer settings, etc., which is much lighter than an xml file. Are you going to do the same process or you stay with the xml, dat and wie files?
Thank you very much.

**Comment by capuderg** [comment]
The functionality of import will stay the same, because they are "standard". These themes that you mention, have their own export/import scripts and with our plugin, we want to enable all theme authors to offer their user easy demo imports with "standard" export files.

**Comment by nicolas92** [comment]
Okay, you're right, thank you :)
