### ISSUE TITLE
Problem import customizer settings

### ISSUE THREAD

**Issue by nicolas92** [proteusthemes/one-click-demo-import#59]
Hello, I have several demos, I uploaded them to github, I retrieved the url that is like this: https://raw.githubusercontent.com/myaccount/sample-data/master/

When I try to import the demos, on some demos, everything works well but on others, I have the following error:

"The customizer import file is not in a correct format. Please make sure to use the correct customizer import file."

Is it possible to solve this problem?

Thank you very much :)

**Comment by capuderg** [comment]
Hi,

this means, that the data of the customizer import file is not correct. Please check, if you are using the correct url to the customizer export file generated by this plugin: https://wordpress.org/plugins/customizer-export-import/

Take care!

**Comment by nicolas92** [comment]
Hello, the url is good, when I enter it in the browser it opens the file but I still have the error on several demos.
When I put the file in local, there is no problem, but when I put the url github, I have this error.
Is there a problem with github?
This may be something else that causes this error that has nothing to do with the customizer file.

**Comment by capuderg** [comment]
I never tested this with github hosted files, but I don't see what the problem could be.

Maybe try hosting the files on your server and see if github is the issue here.

We are hosting the files on our servers and everything is working ok (never had this error).

**Comment by nicolas92** [comment]
Yes on my server it works, but it's too bad, the sample data of my demos are on github, there is no way it works with a url github?
Thank you very much.

**Comment by capuderg** [comment]
As I said, I don't know why the github hosted files wouldn't work, but that is not the plugin's fault...

**Comment by nicolas92** [comment]
It does not matter, I'll put the files locally :)
Thank you.
