### ISSUE TITLE
Elementor Library support

### ISSUE THREAD

**Issue by WPDevHQ** [proteusthemes/one-click-demo-import#60]
Great plugin, thank you for developing it.

Could you possibly consider adding support for the Elementor page builder json import support please?

Elementor: https://github.com/pojome/elementor

**Comment by capuderg** [comment]
Hi,

Thanks! :)

We will not add support for individual page builder or other kind of plugins. If we add support for every single plugin, then this plugin would become bloated and buggy.

This kind of imports (any plugin import functionality) should be hooked to our plugin via the `pt-ocdi/after_import` action hook.
You can probably hook the Elementor specific importer code to the `pt-ocdi/after_import` action hook and it would have to work ok.

Take care!

**Comment by swakarm** [comment]
elementor template is just a post type so you can import it from  wordpress export file with one click demo import.
You will need to select elementor template in place of all while exporting file from wordpress.
