### ISSUE TITLE
Feature Request: Preview Button

### ISSUE THREAD

**Issue by ingeniousweb** [proteusthemes/one-click-demo-import#66]
V2.0 is coming awesome,

Thank you so much for allowing the grid layout and filterable category as requested by many, i have just did a quick test and the ui is really native and awesome, all works fine. However we are still missing the "Preview" button. I request you to please allow a preview url to be passed as well with so the users can preview the demo live (external link).

Thanks,
Munir

![screenshot-testsite dev 2016-12-02 15-46-28](https://cloud.githubusercontent.com/assets/5817882/20836974/b4ba5ca2-b8c3-11e6-83d6-38ea37f13df7.jpg)

**Comment by capuderg** [comment]
Add in https://github.com/proteusthemes/one-click-demo-import/commit/e98e936a148767cdd2b00f4f0ea6b3b518e04a9e

**Comment by capuderg** [comment]
Hi,

the plugin update with this added code was just released (available on https://wordpress.org/plugins/one-click-demo-import/).

If you can, please test is out and let me know, if something is not working as it should.

Take care!

PS: sorry for such a long delay...
