### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by krishna19** [proteusthemes/one-click-demo-import#69]
Whenever I try to activate the plugin I got this error.

Wordpress Version 4.6.1

`Warning: require_once(/Applications/MAMP/htdocs/theme_check/wp-content/plugins/one-click-demo-import-master/vendor/autoload.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/theme_check/wp-content/plugins/one-click-demo-import-master/one-click-demo-import.php on line 38`

`Fatal error: require_once(): Failed opening required '/Applications/MAMP/htdocs/theme_check/wp-content/plugins/one-click-demo-import-master/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.10/lib/php') in /Applications/MAMP/htdocs/theme_check/wp-content/plugins/one-click-demo-import-master/one-click-demo-import.php on line 38`

Thanks

**Comment by capuderg** [comment]
Hi,

did you download the zip file from this github repo? This zip does not have the vendor folder, which is needed for this plugin... This is a developer repository, so PHP composer install must be run in order for it to work.

I would advise you to download the official plugin version (version 1.4.0): https://wordpress.org/plugins/one-click-demo-import/

We are also preparing a new plugin update v2.0.0. And it's currently available here: https://dl.dropboxusercontent.com/u/14641788/OCDI/OCDI-2.0.0-RC2.zip. Ther plugin will be updated in a week or two.

Let me know, if you have any further questions... I'll close this ticket for now, but please reopen it, if there is something else you need.

Take care!

**Comment by krishna19** [comment]
@capuderg Thanks
