### ISSUE TITLE
FS_CHMOD_FILE constant as arg.

### ISSUE THREAD

**Issue by primozcigler** [proteusthemes/one-click-demo-import#7]
Is [here](https://github.com/proteusthemes/one-click-demo-import/blob/master/inc/class-ocdi-helpers.php#L182) any benefit that the 3rd argument is used? `FS_CHMOD_FILE`.

**Comment by primozcigler** [comment]
I believe not, because it will default to this anyway: https://developer.wordpress.org/reference/classes/wp_filesystem_direct/chmod/

**Comment by capuderg** [comment]
You were right, the third argument was not needed...
