### ISSUE TITLE
Failed to import pa_size

### ISSUE THREAD

**Issue by kamiyeye** [proteusthemes/one-click-demo-import#71]
2.0.0 RC2 & WP 4.7

The demo import has finished, but there were some import errors.

> [WARNING] Failed to import pa_size L [WARNING] Failed to import pa_size M [WARNING] Failed to import pa_size S [WARNING] Failed to import pa_size XL [WARNING] Failed to import pa_size XXL 
> [WARNING] Failed to import pa_size L [WARNING] Failed to import pa_size M [WARNING] Failed to import pa_size S [WARNING] Failed to import pa_size XL [WARNING] Failed to import pa_size XXL 
> [WARNING] Failed to import pa_size L [WARNING] Failed to import pa_size M [WARNING] Failed to import pa_size S [WARNING] Failed to import pa_size XL [WARNING] Failed to import pa_size XXL 
> [WARNING] Failed to import pa_size L [WARNING] Failed to import pa_size M [WARNING] Failed to import pa_size S [WARNING] Failed to import pa_size XL [WARNING] Failed to import pa_size XXL 
> [WARNING] Failed to import pa_size L [WARNING] Failed to import pa_size M [WARNING] Failed to import pa_size S [WARNING] Failed to import pa_size XL [WARNING] Failed to import pa_size XXL 
> [WARNING] Failed to import pa_size L [WARNING] Failed to import pa_size M [WARNING] Failed to import pa_size S [WARNING] Failed to import pa_size XL [WARNING] Failed to import pa_size XXL

**Comment by capuderg** [comment]
Hi,

the issue or reporting the same error multiple times is already reported and will be fixed: https://github.com/proteusthemes/one-click-demo-import/issues/68

As for these warnings:

> [WARNING] Failed to import pa_size L 
> [WARNING] Failed to import pa_size M 
> [WARNING] Failed to import pa_size S 
> [WARNING] Failed to import pa_size XL 
> [WARNING] Failed to import pa_size XXL

What are those? Product attributes?

Could you maybe send me the XML file, so I can test it out and see what the problems is?

Take care!

**Comment by kamiyeye** [comment]
I think its WooCommerce product attributes cos the output site has a shop page, how can I send you the XML file?

**Comment by capuderg** [comment]
OK, thanks, I'll test it out with WooCommerce product attributes. No need to send the XML file...

**Comment by capuderg** [comment]
Hi,

It looks like the WooCommerce plugin hooks to the `start_import` action hook and registers the custom taxonomies `pa_*`, when the default WP importer is used to import the data. They have a very specific code for import, so I can't reuse that as is (the code can be found in the plugin file: _woocommerce/includes/admin/class-wc-admin-importers.php_).

I will have to register these "custom taxonomy" for WooCommerce in our plugin, but this is not a high priority issue so it will not be included in the version 2.0.0, which should be release tomorrow, but I will fix this issue for 2.1.0.

Thanks again for reporting this bug!

I'll update this ticket when there will be some progress.

Take care!

**Comment by capuderg** [comment]
Hi @kamiyeye ,

I've fixed the WooCommerce product attributes import issue in the latest version of the plugin v2.1.0 available here: https://wordpress.org/plugins/one-click-demo-import/

Could you please test it with your themes and let me know, if everything works ok now?

Take care!
