### ISSUE TITLE
Trying to use the action before import but not working

### ISSUE THREAD

**Issue by kamiyeye** [proteusthemes/one-click-demo-import#72]
I was trying to change an image size before import so that it generates the right size during import, here is my code:

```
function ocdi_before_content_import( $selected_import ) {
    remove_image_size( 'shop_catalog');
    remove_image_size( 'shop_single');
    remove_image_size( 'shop_thumbnail');
    add_image_size( 'shop_catalog', 930, 1085 );
    add_image_size( 'shop_single', 645, 834, true );
    add_image_size( 'shop_thumbnail', 155, 185, true );
}
add_action( 'pt-ocdi/before_content_import', 'ocdi_before_content_import' );
```

It doesn't work, but removing this code and manually changing the image size before import works.

**Comment by capuderg** [comment]
Hi,

I think that you can't use `remove_image_size` and  `add_image_size` so late in the WP cycle  (before content import). These functions need to be used, when WP is loading up.

You can hook into the `intermediate_image_sizes_advanced` WP filter to change the images sizes. The code of that would look something like this:

```
function ocdi_filter_image_sizes( $sizes ) {
	$sizes['medium']['width']  = 50;
	$sizes['medium']['height'] = 50;
	$sizes['medium']['crop']   = true;

	return $sizes;
}

function ocdi_before_content_import( $selected_import ) {
	add_filter('intermediate_image_sizes_advanced', 'wpmayor_filter_image_sizes' );
}
add_action( 'pt-ocdi/before_content_import', 'ocdi_before_content_import' );
```

Take care!
