### ISSUE TITLE
Termmeta double import

### ISSUE THREAD

**Issue by rufus87novambit** [proteusthemes/one-click-demo-import#78]
Hello.

There is a bug at importing term metas. They are imported twice.

Please see WXRImporter.php
line: 1773 
line: 1798

Thanks.

**Comment by capuderg** [comment]
Hi,

thanks for reporting this bug.

Could you please send me an XML file with term metadata import, so I can test it out and solve this issue. I don't have a XML file like that and we do not use any term metadata in our themes... Would really appreciate it!

Take care!

**Comment by rufus87novambit** [comment]
Hello.

Thank you for the answer.
Please see attached demo-content.xml in demo-content
[demo-content.zip](https://github.com/proteusthemes/one-click-demo-import/files/660966/demo-content.zip)
.zip

**Comment by capuderg** [comment]
Thank you!

I'll probably fix this by the end of this week.

**Comment by rufus87novambit** [comment]
Hello. Thank you.

One more thing.
Is it will be possible to add some checkboxes ( for exmple in demo content importing , when there are multiple demos for one theme ), so user can check what to import ( content, widgets, customizer ).

Did you get my pull request for https://github.com/proteusthemes/one-click-demo-import/pulls

**Comment by capuderg** [comment]
Hi @rufus87novambit ,

I've fixed this issue now in the version 2.1.0 of the plugin. Could you please verify that everything is ok now?

About the checkboxes... this kind of idea is already in the issues list: https://github.com/proteusthemes/one-click-demo-import/issues/48 , but I don't think we will implement it soon, or if we even will...

Take care!
