### ISSUE TITLE
Undefined Variable $exists in WXRImporter.php on line 1325

### ISSUE THREAD

**Issue by Ehsan-Dalvand** [proteusthemes/one-click-demo-import#81]
`PHP Notice:  Undefined variable: exists in .../wp-content/plugins/one-click-demo-import/vendor/proteusthemes/wp-content-importer-v2/src/WXRImporter.php on line 1325, referer: http://***/wp-admin/themes.php?page=pt-one-click-demo-import`

It seems that if something is already exists it gives this notice.

**Comment by capuderg** [comment]
Hi,

thanks for lettings us know about this bug... I've just fixed this and it will be available in the next version of this plugin.

Take care!
