### ISSUE TITLE
WXRImporter.php filesize() problem

### ISSUE THREAD

**Issue by Youhan** [proteusthemes/one-click-demo-import#84]
Hi there, 

Thanks for the great plugin. 

I have faced an issue on some imports on different servers. The problem was that the importer failed to import media files. I have tested the default WordPress Importer plugin using the same XML file and it worked. 

So I tried to check what was wrong. Apparently, the demo server was fine because some servers can import so, the problem was in the importer code. 

After some debugging, I realized that the media files are transferred to the server correctly but then the code that compares the downloaded media file size to the original file is causing an error. Actually, the `filesize()` function `returns 0`. So I changed the code from 

```
$filesize = filesize( $upload['file'] );
``` 
to
```
clearstatcache();
$filesize = filesize( $upload['file'] );

// try again using alternative method.
if ( $filesize == 0 ) {
    $fp = fopen( $upload['file'], "rb" );
    fseek( $fp, 0, SEEK_END );
    $filesize = ftell( $fp );
    fclose( $fp );
}
```

**And it is now importing the media files correctly.**
It still remains a mystery to me why the `filesize()` returns 0 !
Your comment on this is really appreciated.

Thanks

**Comment by capuderg** [comment]
Hi,

hmm... that's strange.

We never had any issues with media imports in our themes.

What kind of files are failing, images, pdfs? What type (png, jpg, ...)?

Are all media files failing or just a few? Are these failed imports always the same files?

This could be a server specific issue...

Could you maybe send me the XML import file, so I can test it out and see, if I get the same results?

Take care!

**Comment by Youhan** [comment]
Hi there, 

I have updated to v2.2.0. I tested on the server which had problems and it is now working again!

Thanks for your time. Let me see if I get those import errors again and I will get deeper into it.

Have a nice day.

**Comment by capuderg** [comment]
Hi,

that's strange, because I didn't change anything regarding the media imports.

Anyway, I will close this issue for now, but let me know, if you find anything new...

Take care!

**Comment by Youhan** [comment]
Hi there, 

It seems that I found what was causing the problem after testing different scenarios! 

The problem is the theme TGMPA recommends to install plugins, one click demo import does that too and recommends to install plugins that the theme needs.

Our theme recommends to install [Ewww Image Optimizer](https://wordpress.org/plugins/ewww-image-optimizer/) and if this plugin is active while you try to import media files, there will be a conflict since this plugin tries to optimize images as soon as they are uploaded. 

Same happens using [Imsanity](https://wordpress.org/plugins/imsanity/) plugin. I have seen lots of error logs generated by Imsanity while demo importer is working.

So, hopefully, that is a good starting point.

Let me know your comment.

Thanks

**Comment by capuderg** [comment]
Hi,

I've never used these kind of plugins, so I can't give you any insights...

I would imagine, that if possible, to disable these plugins before demo content import and enabling  them after the content is importer. There are action hooks in our OCDI plugin, to do so, but I don't know, if there is a function/action hook, that would disable processing of newly uploaded images, that is the territory of theses image optimization plugins and you would have to investigate that.

Take care!
