### ISSUE TITLE
[RESOLVED] Error: OK (200) One Click Demo Import Issue

### ISSUE THREAD

**Issue by ahmadawais** [proteusthemes/one-click-demo-import#86]
I tried OCDI for the first time and plan to use it with my latest premium theme. I configured it as it was written in the article, but on importing the demo both for files hosted locally, or remotely, I got this error.

```php
Error: OK (200)
```

Any insights about why is this happening?

My function looks like this...

```php
/**
 * Demos OCDI.
 *
 * @since 1.0.0
 */
if ( ! function_exists( 'vrc_demos_ocdi' ) ) {
	// Add the filter.
	add_filter( 'pt-ocdi/import_files', 'vrc_demos_ocdi' );

	/**
	 * Functions vrc_demos_ocdi
	 *
	 * @return array
	 * @since  1.0.0
	 */
	function vrc_demos_ocdi() {
		// Return the array.
		return array(
			array(
				'import_file_name'           => 'Demo 01',
				'categories'                 => array( 'General', 'Popular' ),
				'import_file_url'            => 'https://gist.github.com/ahmadawais/***/demo1_content.xml',
				'import_widget_file_url'     => 'https://gist.githubusercontent.com/ahmadawais/***/demo1_widgets.json',
				'import_customizer_file_url' => 'https://gist.github.com/ahmadawais/***/demo1_customizer.dat',
				'import_preview_image_url'   => 'https://i.imgur.com/oTOk38U.jpg',
				'import_notice'              => __( 'After you import this demo, you will have to setup the menu, homepage, and theme.', 'VRC' ),
			),
			array(
				'import_file_name'           => 'Demo 02',
				'categories'                 => array( 'General', 'Popular' ),
				'import_file_url'            => VRC_DIR . '/assets/admin/ocdi/demo2/demo2_content.xml',
				'import_widget_file_url'     => VRC_DIR . '/assets/admin/ocdi/demo2/demo2_widgets.json',
				'import_customizer_file_url' => VRC_DIR . '/assets/admin/ocdi/demo2/demo2_customizer.dat',
				'import_preview_image_url'   => 'https://i.imgur.com/oTOk38U.jpg',
				'import_notice'              => __( 'After you import this demo, you will have to setup the menu, homepage, and theme.', 'VRC' ),
			),
		);
	} // End function.
} // End if().
```

Looking forward!

**Comment by capuderg** [comment]
Hi @ahmadawais,

the setup above looks ok...

Do you have the log file in the Media section? What does the log file say?

Did you use the official plugin zip file: https://wordpress.org/plugins/one-click-demo-import/ ? Or did you download the zip file from GitHub?

**Comment by ahmadawais** [comment]
@capuderg 
1. I used the official plugin. 
2. No nothing got imported
3. I am trying it out on localhost, but it should work, like my other solutions do (hint [Radium OCDI](https://github.com/FrankM1/radium-one-click-demo-install))

**Comment by ahmadawais** [comment]
I tried again on a server and first I got this error.

```php
Error: parsererror (200)
```

Some data was imported but not everything. E.g. `customizer` settings are not there, some are not all.

**Comment by primozcigler** [comment]
Would it be possible that you send us your .xml, .dat and, .json files? It will be easier to debug on our end if we can replicate the problem. (You can send them privately to my email/tw as well if you want).

**Comment by ahmadawais** [comment]
@primozcigler Can you guys point me to some demo files that I could import? That would rule out the possibility of an issue at your end. The demo ain't ready yet so, I won't be able to send it to you guys. I see how bad it looks. Still looking into it.

**Comment by capuderg** [comment]
Hi @ahmadawais,

Here are some very basic/minimal demo import files using the Twenty Fifteen theme:
http://gregorcapuder.com/ocdi/test/twentyfifteen-content.xml
http://gregorcapuder.com/ocdi/test/twentyfifteen-customizer.dat
http://gregorcapuder.com/ocdi/test/twentyfifteen-widgets.json

You can reference these files directly from my server, but let me know, once you are done with them, so I can delete them...

Take care!

**Comment by ahmadawais** [comment]
@capuderg OK, I was able to work through it and have my demos being imported. A few issues here and there. The only problem that I am left with is the meta for post types is not being imported, navigation is also not getting set. Is there some API of OCDI that I could use to call it back to my setup function? Also why would the `page` meta not be getting imported? Any insights on it. 

P.S. The error is gone and demo is getting imported only with the issue explained in this comment. So, I am  marking it resolved for the error mentioned above. It was a file parsing issue, as far as I can see and was at my end.

**Comment by primozcigler** [comment]
@ahmadawais 

> The only problem that I am left with is the meta for post types is not being imported
> Also why would the page meta not be getting imported? Any insights on it.

@capuderg will know more about this. OCDI internally uses @rmccue's https://github.com/humanmade/WordPress-Importer, it might the a bug from there.

> navigation is also not getting set. Is there some API of OCDI that I could use to call it back to my setup function?

Yes, there are hooks for that, explained in the FAQ: https://github.com/proteusthemes/one-click-demo-import#how-to-automatically-assign-front-page-posts-page-and-menu-locations-after-the-importer-is-done

**Comment by ahmadawais** [comment]
@primozcigler Thanks for that. I probably missed it, I think read me needs some love. Just sent an PR #89

**Comment by capuderg** [comment]
hm... nobody reported issues with any post_type meta data import.

We are using the "new" WP importer as Primož said, well, actually we are using a fork of it, with some bug fixes and PSR-4 autoloader: https://github.com/proteusthemes/WordPress-Importer

It would be good, if you could send us the content import files, so we could debug the issue...

**Comment by ahmadawais** [comment]
@capuderg I was able to work it out — thanks a lot.

**Comment by capuderg** [comment]
@ahmadawais great!

Could you just let us know, what the issue with `parser error` was? Was it a strange character in the content XML import file?

And also what was the issue with the post type meta data?

It's always good to know, what the issue is, so we can fix it in the plugin or maybe we can write it in the docs, so other with the same issues can find the solution...

Thanks!

**Comment by ahmadawais** [comment]
Sure! Both the issues were at my end. I had a strange character at the
start of xml file I think I put it there while saving it. The meta data got
imported when I tried again. WP-RESET plugin came in handy and I am still
working on the demo import thing so, I didn't comment.

**Comment by capuderg** [comment]
Thanks for sharing!

Let me know, if you need anything else.
