### ISSUE TITLE
Improve the design of the plugin import page

### ISSUE THREAD

**Issue by capuderg** [proteusthemes/one-click-demo-import#9]
- [x] Apply the design changes from Jaka,

- [x] Make screenshots and add them to the readme.txt!

- [x] Add banner and icon to the plugin assets directory

**Comment by anteksiler** [comment]
@capuderg It would be nice to add a filter to disable page creation.

**Comment by capuderg** [comment]
@anteksiler what do you mean "disable page creation"? What would be the use-case for such filter?

**Comment by anteksiler** [comment]
I integrated this plugin with the option-tree framework. So I do not need the plugin pages :)

**Comment by capuderg** [comment]
In the latest version of this plugin I added a filter called `pt-ocdi/plugin-page-setup`, which you could use, to "hide" the plugin page. The code would look something like this:

```
function ocdi_plugin_page_setup( $default_settings ) {
	$default_settings['parent_slug'] = false;

	return $default_settings;
}
add_filter( 'pt-ocdi/plugin-page-setup', 'ocdi_plugin_page_setup' );
```

But in the next version of the plugin the filter will be changed from 'pt-ocdi/plugin-page-setup' to 'pt-ocdi/plugin_page_setup' (I made a naming mistake in the previous version).

This should work for your use case and that's why I will not add a seperate filter to disable the plugin page.

Take care!

**Comment by capuderg** [comment]
Screenshots have been uploaded to the WP plugin repo...

**Comment by shofer4eto** [comment]
Hey @anteksiler,

Would you please share your solution for the Option Tree plugin integration? Would love to do that too!
Disabling the OCDI plugin pages would also be something I am interested in. Thanks a lot in advance, friend!
