### ISSUE TITLE
Double import custom post type

### ISSUE THREAD

**Issue by vlthemes** [proteusthemes/one-click-demo-import#90]
Hi Proteus!

How can I change double import for the custom post type?

Thanks :)

**Comment by capuderg** [comment]
Hi,

what exactly do you mean?

When you import the second time, the custom post type posts get imported again, making duplicates?

Why are you importing the second time (is the import not complete the first time)?

Take care!

**Comment by vlthemes** [comment]
Yes, posts duplicated. I pressed a second time to simulate client.
http://take.ms/mej8T

P.S. I`m author on TF and I wanted to install this plugin a new theme. https://themeforest.net/user/vlthemes

**Comment by capuderg** [comment]
Hi,

The posts and pages do not duplicate, right? The problem is just in the custom post type?

I still don't understand, why a client would run the demo import multiple time?

I'll take a look at this problem, but I can't say when exactly that will be.

Take care!

**Comment by vlthemes** [comment]
For example https://monosnap.com/file/M8XZpwLm179ZevTrvXBQwNGRDQCpky

I have 2 demo and one xml file.

**Comment by capuderg** [comment]
Hi,

I've fixed this custom post type duplication issue. Please test it on your site using this plugin zip file: https://dl.dropboxusercontent.com/u/14641788/OCDI/one-click-demo-import-cpt-duplicate-fix.zip

Let me know how it goes.

Take care!

**Comment by vlthemes** [comment]
Hooray!!! Thank you very much, it works :)

**Comment by capuderg** [comment]
Hi,

great! :)

I'll probably make an official plugin update in two weeks or so.

Take care!

**Comment by capuderg** [comment]
Hi @vlthemes,

it's been a bit more then two weeks, but it's here now. The OCDI version 2.2.1 is now live :)

Take care!

**Comment by vlthemes** [comment]
Ty so much. You are the best.
Пн, 3 апр. 2017 г. в 18:22, capuderg <notifications@github.com>:
