### ISSUE TITLE
Import sticky post and ordering post

### ISSUE THREAD

**Issue by vlthemes** [proteusthemes/one-click-demo-import#91]
And I dont know, is it bug or no.

Not added sticky option to the post.

**Comment by capuderg** [comment]
Hi,

the sticky post imports ok for our themes: [screenshot](http://www.awesomescreenshot.com/image/2190566/78d0296e4d380852805a51f6fd858b6c).

What do you mean with "post ordering"?

Take care!

**Comment by vlthemes** [comment]
Yep, sorry. I set it up incorrectly.

I use this plug-in to post ordering (https://wordpress.org/plugins/intuitive-custom-post-order/), but demo importer is bound to the date of creation.

And thanks for the plugin. Very good support! :)

**Comment by capuderg** [comment]
Hi,

I'm sorry, but I can't help you with this post ordering issue, since this is not a part of the WP core.

Thanks for the kind words :)

Take care!
