### ISSUE TITLE
Revolution Slider import

### ISSUE THREAD

**Issue by DeliciousThemes** [proteusthemes/one-click-demo-import#93]
Hey guys,

I want to let you know that this is an awesome plugin! 

I have a question, though. Is there any way to import a Rev Slider demo slider as well, together with the default content? 

Thanks!

**Comment by DeliciousThemes** [comment]
I might've found the answer to my question. 

Here's a PHP snippet from ThemePunch for auto importing those sliders https://www.themepunch.com/faq/theme-authors-auto-import-slider-demos/ and a nice guide for implementing the one-click import functionality into wp themes, along with the revslider demos http://www.themevan.com/a-simple-guide-to-provide-one-click-demo-import-feature-in-wordpress/

All the best!

**Comment by capuderg** [comment]
Hi @DeliciousThemes,

thanks for the kind words :)

And also thanks for sharing these links. I'm sure it will be useful to other users as well!

Take care!

PS: please rate the plugin here: https://wordpress.org/support/plugin/one-click-demo-import/reviews/, we would really appreciate it! :)
